
package com.unf.edu.wsat.balanceinquiry;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "BalanceInquiryException", targetNamespace = "http://jaxws.balanceinquiry.wsat.edu.unf.com/")
public class BalanceInquiryException
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private com.unf.edu.wsat.balanceinquiry.jaxws.BalanceInquiryException faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public BalanceInquiryException(String message, com.unf.edu.wsat.balanceinquiry.jaxws.BalanceInquiryException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public BalanceInquiryException(String message, com.unf.edu.wsat.balanceinquiry.jaxws.BalanceInquiryException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.unf.edu.wsat.balanceinquiry.jaxws.BalanceInquiryException
     */
    public com.unf.edu.wsat.balanceinquiry.jaxws.BalanceInquiryException getFaultInfo() {
        return faultInfo;
    }

}
