
package com.unf.edu.wsat.balanceinquiry;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "BalanceInquiryATImplService", targetNamespace = "http://balanceinquiry.wsat.edu.unf.com/", wsdlLocation = "http://localhost:8080/BalanceInquiry/BalanceInquiryATImpl?wsdl")
public class BalanceInquiryATImplService
    extends Service
{

    private final static URL BALANCEINQUIRYATIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException BALANCEINQUIRYATIMPLSERVICE_EXCEPTION;
    private final static QName BALANCEINQUIRYATIMPLSERVICE_QNAME = new QName("http://balanceinquiry.wsat.edu.unf.com/", "BalanceInquiryATImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/BalanceInquiry/BalanceInquiryATImpl?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BALANCEINQUIRYATIMPLSERVICE_WSDL_LOCATION = url;
        BALANCEINQUIRYATIMPLSERVICE_EXCEPTION = e;
    }

    public BalanceInquiryATImplService() {
        super(__getWsdlLocation(), BALANCEINQUIRYATIMPLSERVICE_QNAME);
    }

    public BalanceInquiryATImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), BALANCEINQUIRYATIMPLSERVICE_QNAME, features);
    }

    public BalanceInquiryATImplService(URL wsdlLocation) {
        super(wsdlLocation, BALANCEINQUIRYATIMPLSERVICE_QNAME);
    }

    public BalanceInquiryATImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BALANCEINQUIRYATIMPLSERVICE_QNAME, features);
    }

    public BalanceInquiryATImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BalanceInquiryATImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns BalanceInquiryAT
     */
    @WebEndpoint(name = "BalanceInquiryATImplPort")
    public BalanceInquiryAT getBalanceInquiryATImplPort() {
        return super.getPort(new QName("http://balanceinquiry.wsat.edu.unf.com/", "BalanceInquiryATImplPort"), BalanceInquiryAT.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BalanceInquiryAT
     */
    @WebEndpoint(name = "BalanceInquiryATImplPort")
    public BalanceInquiryAT getBalanceInquiryATImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://balanceinquiry.wsat.edu.unf.com/", "BalanceInquiryATImplPort"), BalanceInquiryAT.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BALANCEINQUIRYATIMPLSERVICE_EXCEPTION!= null) {
            throw BALANCEINQUIRYATIMPLSERVICE_EXCEPTION;
        }
        return BALANCEINQUIRYATIMPLSERVICE_WSDL_LOCATION;
    }

}
