
package com.unf.edu.wsat.balanceinquiry;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import com.unf.edu.wsat.balanceinquiry.jaxws.ObjectFactory;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "BalanceInquiryAT", targetNamespace = "http://jaxws.balanceinquiry.wsat.edu.unf.com/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BalanceInquiryAT {


    /**
     * 
     * @return
     *     returns long
     */
    @WebMethod
    @WebResult(partName = "return")
    public long generateBalanceAmount();

    /**
     * 
     * @param arg0
     * @throws BalanceInquiryException
     */
    @WebMethod
    public long getBalance(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0)
        throws BalanceInquiryException
    ;

}
